### ISSUE TITLE
Figma Designs erstellen

### ISSUE THREAD

**Issue by BiederneBachstelze** [Doner-mit-alles/wirtschaft-live#1]
- In Figma einarbeiten
- 3 Beispiel Designs erstellen anhand der Kundenvorlage

**Comment by Huss15** [comment]
Ich habe mal mit einem Desgin angefangen
https://www.figma.com/proto/ps4E1Pon1ukVtog4oivrFe/LF10_Mockup?t=XsxTrlFJydIQJtXQ-1&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&node-id=26-225&starting-point-node-id=26%3A225

**Comment by Huss15** [comment]
https://www.figma.com/design/ps4E1Pon1ukVtog4oivrFe/LF10_Mockup?node-id=26-225&t=ypMqwik8yDDEOGJk-1
